### ISSUE TITLE
Cannot run client side webpack server

### ISSUE THREAD

**Issue by xChristianZx** [chingu-voyage6/Bears-Team-02#8]
@rmorabia I tried running the client, and while 8080 is being served, we're not getting a root output for it.

Could you please add /public folder with index.html and a /src folder with an index.js so we could get a running client side setup.  Thanks!

Stack trace is below - 

![image](https://user-images.githubusercontent.com/20914658/41425507-d56837f8-6fb5-11e8-8c17-f96173b586ad.png)

**Comment by rmorabia** [comment]
Fixed in Commit #6c51e0d.

**Comment by xChristianZx** [comment]
Just tested it out on my end, and it all looks good.  `app.js` should be fine for now.  It will all get moved around as we start laying out components.
